# Node.js with Vue
# Build a Node.js project that uses Vue.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm build
  displayName: 'npm install and build'

- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Azure for Students(bcc318b7-3b03-43a8-b3b4-71ddba8ab0fd)'
    appType: 'webAppLinux'
    WebAppName: 'test-bath-reserve-console'
    deployToSlotOrASE: true
    ResourceGroupName: 'my_resource'
    SlotName: 'production'
    packageForLinux: '$(System.DefaultWorkingDirectory)/dist/*'
    RuntimeStack: 'NODE|14-lts'
